version: "3.3"

services:
  db:
    image: postgres
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/code

  web:
    build: .
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && gunicorn yarn.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - web

volumes:
  code: